export const cartExample = [
  {
    productId: String(Math.random()),
    image: 'latte',
    name: 'Latte',
    value: 9.9,
    quantity: 1,
  },
  {
    productId: String(Math.random()),
    image: 'expresso-gelado',
    name: 'Expresso Gelado Italiano Premium',
    value: 19.9,
    quantity: 1,
  },
  {
    productId: String(Math.random()),
    image: 'arabe',
    name: 'Árabe',
    value: 4.9,
    quantity: 1,
  },
  {
    productId: String(Math.random()),
    image: 'latte',
    name: 'Latte',
    value: 9.9,
    quantity: 1,
  },
  {
    productId: String(Math.random()),
    image: 'expresso-gelado',
    name: 'Expresso Gelado Italiano Premium',
    value: 19.9,
    quantity: 1,
  },
  {
    productId: String(Math.random()),
    image: 'arabe',
    name: 'Árabe',
    value: 4.9,
    quantity: 1,
  },
  {
    productId: String(Math.random()),
    image: 'latte',
    name: 'Latte',
    value: 9.9,
    quantity: 1,
  },
  {
    productId: String(Math.random()),
    image: 'expresso-gelado',
    name: 'Expresso Gelado Italiano Premium',
    value: 19.9,
    quantity: 1,
  },
  {
    productId: String(Math.random()),
    image: 'arabe',
    name: 'Árabe',
    value: 4.9,
    quantity: 1,
  },
];
