import { Input } from './Form.types';

export const inputs: Input[] = [
  { name: 'CEP', type: 'text', isRequired: true },
  { name: 'Rua', type: 'text', isRequired: true },
  { name: 'Número', type: 'text', isRequired: true },
  { name: 'Complemento', type: 'text', isRequired: false },
  { name: 'Bairro', type: 'text', isRequired: true },
  { name: 'Cidade', type: 'text', isRequired: true },
  {
    name: 'UF',
    type: 'select',
    isRequired: true,
    options: [
      'AC',
      'AL',
      'AM',
      'AP',
      'BA',
      'CE',
      'DF',
      'ES',
      'GO',
      'MA',
      'MG',
      'MS',
      'MT',
      'PA',
      'PB',
      'PE',
      'PI',
      'PR',
      'RJ',
      'RN',
      'RO',
      'RR',
      'RS',
      'SC',
      'SE',
      'SP',
      'TO',
    ],
  },
];
